name: The Cathedral
author: Tyler Yasaka
url:
baseurl: https://thecathedral.io
resume_site: https://tyleryasaka.github.io
description:
github_username: tyleryasaka
github:
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ["README.md", "Gemfile.lock", "Gemfile", "Rakefile"]
highlighter: rouge
markdown: kramdown
comments:
  gitalk:
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
